name: 'wonejomb-webhook-actions'
author: 'WonejoMB'
description: 'Send better discord embeds with webhooks'
inputs:
  webhook_url:
    description: 'The discord webhook URL'
    required: true
  webhook_avatar:
    description: 'The dicord webhook avatar'
    required: false
    default: 'https://avatars.githubusercontent.com/in/15368?v=4'
  webhook_name:
    description: 'The discord webhook name'
    required: false
    default: 'Github Actions'
env:
  GITHUB_TOKEN: ${{ github.token }};

runs:
  using: 'node20'
  main: 'src/index.js'